using System.Collections.Generic;
using System.IO;
using System.Text;
using HerOClock.Characters;
using UnityEditor;
using UnityEngine;

namespace HerOClock.EditorTools
{
    /// <summary>
    /// Points every character sheet at its drawings, by file name.
    ///
    /// A tie to a sprite is stored as a file id generated by Unity on import, and that id cannot
    /// be written into a `.asset` from outside the editor without guessing it. A wrong guess
    /// shows up as "Missing (Sprite)" rather than as an error. So the tie is made here, where the
    /// sprite is asked for by path and Unity hands back whatever id it actually used.
    ///
    /// The convention is the character id plus the direction: a sheet with the id `tempo` looks
    /// for `tempo-down`, `tempo-up`, `tempo-side` and `tempo-dead` under Assets/Art/Characters.
    /// Anything missing is left alone, so a character without art keeps its rectangle.
    /// </summary>
    public static class CharacterSpriteLinker
    {
        private const string ArtRoot = "Assets/Art";
        private const string Folder = "Assets/Art/Characters/";

        [MenuItem("Her-o-clock/Link character sprites")]
        public static void Link()
        {
            StringBuilder report = new StringBuilder();

            Repair(report);

            int linked = 0;
            string[] guids = AssetDatabase.FindAssets("t:" + nameof(CharacterDefinition));
            report.AppendLine("Sheets found: " + guids.Length);

            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                CharacterDefinition definition = AssetDatabase.LoadAssetAtPath<CharacterDefinition>(path);

                if (definition == null || string.IsNullOrEmpty(definition.Id))
                {
                    continue;
                }

                // A sheet serialised before the field existed comes back with it null.
                if (definition.Sprites == null)
                {
                    definition.Sprites = new View.CharacterSprites();
                }

                List<string> found = new List<string>();

                if (Assign(definition.Id, "down", ref definition.Sprites.Down, found)) { linked++; }
                if (Assign(definition.Id, "up", ref definition.Sprites.Up, found)) { linked++; }
                if (Assign(definition.Id, "side", ref definition.Sprites.Side, found)) { linked++; }
                if (Assign(definition.Id, "dead", ref definition.Sprites.Dead, found)) { linked++; }
                if (AssignSequence(definition.Id, "attack-melee", ref definition.Sprites.AttackMelee, found)) { linked++; }
                if (AssignSequence(definition.Id, "attack-ranged", ref definition.Sprites.AttackRanged, found)) { linked++; }
                if (AssignSequence(definition.Id, "run", ref definition.Sprites.Run, found)) { linked++; }

                if (found.Count == 0)
                {
                    continue;
                }

                EditorUtility.SetDirty(definition);
                report.AppendLine("  " + definition.Id + ": " + string.Join(", ", found));
            }

            AssetDatabase.SaveAssets();

            if (linked == 0)
            {
                Debug.LogWarning("Link character sprites: nothing was linked.\n" + report);
                return;
            }

            Debug.Log("Link character sprites: " + linked + " linked.\n" + report);
        }

        /// <summary>
        /// Rebuilds any drawing that the asset database knows about but cannot hand over.
        ///
        /// The database listing a texture while refusing to load it means the import produced
        /// nothing. The editor does not always recover from that on its own and does not always
        /// report it: it shows up as a red cross on the icon in the Project window and as a field
        /// that reads "Missing".
        ///
        /// Deleting the `.meta` is deliberate. A failed import can be recorded in the meta
        /// itself, and starting from a fresh one is the only way past that. It is safe here
        /// precisely because nothing refers to a drawing by its id: every tie is made by path,
        /// right below, so a new id costs nothing.
        /// </summary>
        private static void Repair(StringBuilder report)
        {
            string[] guids = AssetDatabase.FindAssets("t:Texture2D", new[] { ArtRoot });
            List<string> broken = new List<string>();

            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);

                if (AssetDatabase.LoadAssetAtPath<Texture2D>(path) == null)
                {
                    broken.Add(path);
                }
            }

            report.AppendLine("Drawings under " + ArtRoot + ": " + guids.Length
                + ", of which " + broken.Count + " would not load.");

            if (broken.Count == 0)
            {
                return;
            }

            foreach (string path in broken)
            {
                string meta = path + ".meta";

                if (File.Exists(meta))
                {
                    File.Delete(meta);
                }
            }

            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);

            foreach (string path in broken)
            {
                AssetDatabase.ImportAsset(path,
                    ImportAssetOptions.ForceUpdate | ImportAssetOptions.ForceSynchronousImport);

                bool texture = AssetDatabase.LoadAssetAtPath<Texture2D>(path) != null;
                bool sprite = AssetDatabase.LoadAssetAtPath<Sprite>(path) != null;
                report.AppendLine("  rebuilt " + path + "  texture=" + texture + "  sprite=" + sprite);
            }
        }

        /// <summary>
        /// Loads a numbered sequence and stops at the first gap.
        ///
        /// Stopping at the gap rather than scanning a fixed count means a sequence can be any
        /// length, and a half delivered one plays as far as it goes instead of throwing. A single
        /// unnumbered file is accepted too, so a one drawing swing needs no `-0` on the end.
        /// </summary>
        private static bool AssignSequence(string id, string name, ref Sprite[] field, List<string> found)
        {
            List<Sprite> frames = new List<Sprite>();

            for (int i = 0; ; i++)
            {
                Sprite frame = AssetDatabase.LoadAssetAtPath<Sprite>(Folder + id + "-" + name + "-" + i + ".png");

                if (frame == null)
                {
                    break;
                }

                frames.Add(frame);
            }

            if (frames.Count == 0)
            {
                Sprite single = AssetDatabase.LoadAssetAtPath<Sprite>(Folder + id + "-" + name + ".png");

                if (single != null)
                {
                    frames.Add(single);
                }
            }

            if (frames.Count == 0)
            {
                return false;
            }

            field = frames.ToArray();
            found.Add(name + " x" + frames.Count);
            return true;
        }

        /// <summary>
        /// Loads one drawing and puts it in its field.
        ///
        /// A file that is not there is normal and says nothing. A file that is there and still
        /// does not come back as a sprite has already been reported by <see cref="Repair"/>.
        /// </summary>
        private static bool Assign(string id, string direction, ref Sprite field, List<string> found)
        {
            Sprite sprite = AssetDatabase.LoadAssetAtPath<Sprite>(Folder + id + "-" + direction + ".png");

            if (sprite == null)
            {
                return false;
            }

            field = sprite;
            found.Add(direction);
            return true;
        }
    }
}
